CREATE TABLE `2023` (
    DATA DATE,
    REG_ANS INT,
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

CREATE TABLE `2024` (
    DATA DATE,
    REG_ANS INT,
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO VARCHAR(255),
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

LOAD DATA INFILE 'C:/Users/igorj/OneDrive/Documentos/Code/Repositorios/Intuitive/3. SQL/2023/4T2023.csv'
INTO TABLE `2023`
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(@DATA, @REG_ANS, @CD_CONTA_CONTABIL, @DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
    REG_ANS = CAST(@REG_ANS AS UNSIGNED),
    CD_CONTA_CONTABIL = @CD_CONTA_CONTABIL,
    DESCRICAO = @DESCRICAO,
    VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
    VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.');

    
SELECT * FROM `2023`;

LOAD DATA INFILE 'C:/Users/igorj/OneDrive/Documentos/Code/Repositorios/Intuitive/3. SQL/2024/4T2024.csv'
INTO TABLE `2024`
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL)
SET 
    DATA = STR_TO_DATE(TRIM(BOTH '"' FROM @DATA), '%d/%m/%Y'),
    VL_SALDO_INICIAL = REPLACE(TRIM(BOTH '"' FROM @VL_SALDO_INICIAL), ',', '.'),
    VL_SALDO_FINAL = REPLACE(TRIM(BOTH '"' FROM @VL_SALDO_FINAL), ',', '.');